### ISSUE TITLE
Script fails with "Exception occurred while executing 'grant':"

### ISSUE THREAD

**Issue by pmead7399** [mrrfv/linux-android-backup#40]
Let me start by saying I'm not on the developer level for understanding everything that goes on with the script and it is possible that I am doing something or not doing something and that it's just me...

So I run sudo ./backup.sh, enter my password it asks me a series of question, developer mode is enable, adb debugging is enabled, adb devices sees the device, I select tar, wired, no hooks, backup (I think that's all) it starts, looks good for a bit, here are the last 3 lines before the error

`Performing Streamed Install
Success
Granting required permissions to companion app.`

and then....

`Exception occurred while executing 'grant':
java.lang.SecurityException: grantRuntimePermission: Neither user 2000 nor current process has android.permission.GRANT_RUNTIME_PERMISSIONS.
	at android.app.ContextImpl.enforce(ContextImpl.java:2187)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2215)
	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermissionInternal(PermissionManagerService.java:1470)
	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1452)
	at android.permission.PermissionManager.grantRuntimePermission(PermissionManager.java:378)
	at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2419)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:260)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:25791)
	at android.os.Binder.shellCommand(Binder.java:970)
	at android.os.Binder.onTransact(Binder.java:854)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4818)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:8879)
	at android.os.Binder.execTransactInternal(Binder.java:1226)
	at android.os.Binder.execTransact(Binder.java:1163)
`

If you need any more info lmk, I'm using OnePlus 10 Pro, Tmo variant  Android 12 if any of that matrters..

Thank you

**Comment by mrrfv** [comment]
Do you have Island or Shelter installed, multiple users, or a guest user enabled on your device? You should be able to work around this problem by commenting out lines 179-182 as the perms are automatically granted only for the user's convenience.

https://github.com/mrrfv/linux-android-backup/blob/980063aa98557d723a940d7ce1d98a6e8fc0b9be/backup.sh#L179-L182

(please don't ignore or close this issue if the workaround works)
